version: 2

sources:
  - name: gz_raw_data
    database: amazing-insight-419011
    schema: gz_raw_data
    description: "Holds raw data related to sales, products, and shipping."
    tables:
      - name: raw_gz_sales
        description: "Details of transactions."
        columns:
          - name: date_date
            description: "Date of transaction."
            data_type: "date"
            tests:
              - not_null
          - name: orders_id
            description: "Identifier for orders."
            data_type: "integer"
            tests:
              - not_null
          - name: product_id
            description: "Identifier for products."
            data_type: "integer"
          - name: revenue
            description: "Revenue from transaction."
            data_type: "numeric"
          - name: quantity
            description: "Quantity of products sold."
            data_type: "integer"
      - name: raw_gz_product
        description: "Product information."
        columns:
          - name: products_id
            description: "Identifier for products."
            data_type: "integer"
          - name: purchase_price
            description: "Purchase price of products."
            data_type: "numeric"
      - name: raw_ship
        description: "Shipping information for orders."
        columns:
          - name: orders_id
            description: "Identifier for orders."
            data_type: "integer"
          - name: shipping_fee
            description: "Fee for shipping."
            data_type: "numeric"
          - name: log_cost
            description: "Cost of logistics."
            data_type: "numeric"
          - name: ship_cost
            description: "Actual cost of shipping."
            data_type: "numeric"
      - name: raw_gz_adwords
        description: "Google AdWords campaign data."
        columns:
          - name: date_date
            description: "Ad display date."
            data_type: "date"
            tests:
              - not_null
          - name: paid_source
            description: "Ad payment platform."
            data_type: "string"
            tests:
              - not_null
          - name: campaign_key
            description: "Campaign identifier."
            data_type: "integer"
            tests:
              - not_null
          - name: camPGN_name
            description: "Campaign name."
            data_type: "string"
            tests:
              - not_null
          - name: ads_cost
            description: "Cost of ads."
            data_type: "numeric"
            tests:
              - not_null
          - name: impression
            description: "Ad impressions."
            data_type: "numeric"
            tests:
              - not_null
          - name: click
            description: "Ad clicks."
            data_type: "numeric"
            tests:
              - not_null
      - name: raw_gz_criteo
        description: "Criteo advertising data."
        columns:
          - name: date_date
            description: "Ad display date."
            data_type: "date"
            tests:
              - not_null
          - name: paid_source
            description: "Ad payment platform."
            data_type: "string"
            tests:
              - not_null
          - name: campaign_key
            description: "Campaign identifier."
            data_type: "string"
            tests:
              - not_null
          - name: camPGN_name
            description: "Campaign name."
            data_type: "string"
            tests:
              - not_null
          - name: ads_cost
            description: "Cost of ads."
            data_type: "numeric"
            tests:
              - not_null
          - name: impression
            description: "Ad impressions."
            data_type: "numeric"
            tests:
              - not_null
          - name: click
            description: "Ad clicks."
            data_type: "numeric"
            tests:
              - not_null
      - name: raw_gz_facebook
        description: "Facebook advertising data."
        columns:
          - name: date_date
            description: "Ad display date."
            data_type: "date"
            tests:
              - not_null
          - name: paid_source
            description: "Ad payment platform."
            data_type: "string"
            tests:
              - not_null
          - name: campaign_key
            description: "Campaign identifier."
            data_type: "string"
            tests:
              - not_null
          - name: camPGN_name
            description: "Campaign name."
            data_type: "string"
            tests:
              - not_null
          - name: ads_cost
            description: "Cost of ads."
            data_type: "numeric"
            tests:
              - not_null
          - name: impression
            description: "Ad impressions."
            data_type: "numeric"
            tests:
              - not_null
          - name: click
            description: "Ad clicks."
            data_type: "numeric"
            tests:
              - not_null

models:
  - name: int_campaigns_day
    description: >
      This model aggregates advertising data from multiple sources (Google AdWords, Criteo, and Facebook).
      It provides a daily summary of ad costs, impressions, and clicks. It is useful for tracking
      the performance of marketing campaigns across different platforms on a day-to-day basis.

    columns:
      - name: date_date
        description: The date of the data record, representing the day for which the advertising data was aggregated.
        tests:
          - not_null
          - unique

      - name: ads_cost
        description: Total advertising cost accumulated on this date across all platforms.
        tests:
          - not_null

      - name: impression
        description: Total number of ad impressions on this date across all platforms.
        tests:
          - not_null

      - name: click
        description: Total number of ad clicks on this date across all platforms.
        tests:
          - not_null

